plugins {
	id 'java'
	id 'maven-publish'
	id 'org.springframework.boot' version '3.4.2-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = "com.example"
version = "1.0.0"

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/snapshot' }
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

ext {
	JUNIT_VERSION = '5.11.4'
	LOMBOK_VERSION = '1.18.22'
}

dependencies {
	// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation
	implementation 'org.springframework.boot:spring-boot-starter-validation:3.4.1'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	compileOnly "org.projectlombok:lombok:${LOMBOK_VERSION}" // Use the latest version
	annotationProcessor "org.projectlombok:lombok:${LOMBOK_VERSION}"

	// https://mvnrepository.com/artifact/org.junit/junit-bom
	testImplementation "org.junit:junit-bom:${JUNIT_VERSION}"
	// https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter
	testImplementation "org.junit.jupiter:junit-jupiter:${JUNIT_VERSION}"

}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
	repositories {
		mavenLocal()
	}
}

tasks.test {
	useJUnitPlatform()
}